<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp"  />
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="Newtonsoft.Json"  />
    <PackageReference Include="NSubstitute"  />
    <PackageReference Include="NUnit"  />
    <PackageReference Include="NUnit3TestAdapter"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ObjectsComparer\ObjectsComparer.csproj" />
  </ItemGroup>
</Project>